### PR TITLE
Add support for downloading saved cards

### LINKED ISSUE #12: Could there be an option to export saved units?
I know you can export them to png, but it would be really useful to be able to export them as an object that could then be edited somewhere else easily.

### PR DESCRIPTION
**Pull request by chaughawout**
Added support for downloading all saved cards. Resolves #12.

I haven't been able to test this at all yet locally.  What version of node is being used?

I added several dependencies manually to package.json so they aren't in the package-json.lock or anything.

Could you help me get this over the finish line @freddybushboy?

### CODE REVIEW

**Comment by chaughawout** [comment]
I saw that react-scripts needs node v10.16.0 or later. I can give a stab at testing this out more thoroughly soon.

**Comment by freddybushboy** [comment]
I'll take a look :)

**Comment by freddybushboy** [comment]
I checked it out locally and it doesn't seem to work, happy to get this out there once you get it working though. I made a few small changes to get the linter happy again, hopefully that helps!

Im using node `v12.20.1`

**Comment by chaughawout** [comment]
@freddybushboy this has been updated and is now functioning as expected! I have a todo comment about a hard-coded style value that's used to get the width of the card images set correctly. Let me know how you recommend to fix that and I believe that it will be in a good spot to move forward with!

**Review by freddybushboy — APPROVED** [review]

**Comment by freddybushboy** [comment]
It's live! Thanks for this - great feature 🎉

**Pull request merged**
